<?php

use Illuminate\Database\Seeder;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrPaises = array('AFGANISTAN', 'AFRICA DEL SUR', 'ALBANIA', 'ALEMANIA', 'ANDORRA', 'ANGOLA', 'ANTIGUA Y BARBUDA', 'ANTILLAS HOLANDESAS', 'ARABIA SAUDITA'
,'ARGELIA','ARGENTINA', 'ARMENIA', 'ARUBA', 'AUSTRALIA', 'AUSTRIA','AZERBAIJAN','BAHAMAS', 'BAHRAIN', 'BANGLADESH', 'BARBADOS', 'BELARUSIA', 'BELGICA', 'BELICE',
 'BENIN', 'BERMUDAS', 'BOLIVIA', 'BOSNIA', 'BOTSWANA', 'BRASIL', 'BRUNEI DARUSSULAM', 'BULGARIA', 'BURKINA FASO', 'BURUNDI', 'BUTAN', 'CAMBOYA', 'CAMERUN', 'CANADA',
'CAPE VERDE', 'CHAD', 'CHILE', 'CHINA', 'CHIPRE', 'COLOMBIA', 'COMOROS', 'CONGO', 'COREA DEL NORTE', 'COREA DEL SUR', 'COSTA DE MARFÍL', 'COSTA RICA', 'CROASIA', 
'CUBA', 'DINAMARCA', 'DJIBOUTI','DOMINICA', 'ECUADOR', 'EGIPTO', 'EL SALVADOR', 'EMIRATOS ARABES UNIDOS', 'ERITREA', 'ESLOVENIA', 'ESPAÑA', 'ESTADOS UNIDOS', 'ESTONIA',
 'ETIOPIA', 'FIJI', 'FILIPINAS', 'FINLANDIA', 'FRANCIA', 'GABON', 'GAMBIA', 'GEORGIA', 'GHANA', 'GRANADA', 'GRECIA', 'GROENLANDIA', 'GUADALUPE', 'GUAM', 'GUATEMALA',
'GUAYANA FRANCESA', 'GUERNEY', 'GUINEA', 'GUINEA-BISSAU', 'GUINEA EQUATORIAL', 'GUYANA', 'HAITI', 'HOLANDA', 'HONDURAS', 'HONG KONG', 'HUNGRIA', 'INDIA', 'INDONESIA',
'IRAK', 'IRAN', 'IRLANDA', 'ISLANDIA', 'ISLAS CAIMAN', 'ISLAS FAROE', 'ISLAS MALVINAS', 'ISLAS MARSHALL', 'ISLAS SOLOMON', 'ISLAS VIRGENES BRITANICAS', 'ISLAS VIRGENES (U.S.)', 'ISRAEL', 'ITALIA', 'JAMAICA', 'JAPON', 'JERSEY', 'JJORDANIAJO', 'KAZAKHSTAN', 'KENIA', 'KIRIBATI', 'KUWAIT', 'KYRGYZSTAN', 'LAOS', 'LATVIA', 'LESOTHO',
'LIBANO','LIBERIA','LIBIA','LIECHTENSTEIN','LITUANIA','LUXEMBURGO','MACAO','MACEDONIA','MADAGASCAR','MALASIA','MALAWI','MALDIVAS','MALI','MALTA','MARRUECOS','MARTINICA','MAURICIO','MAURITANIA','MEXICO','MICRONESIA','MOLDOVA','MONACO','MONGOLIA','MOZAMBIQUE','MYANMAR (BURMA)','NAMIBIA','NEPAL','NICARAGUA','NIGER','NIGERIA','NORUEGA','NUEVA CALEDONIA','NUEVA ZEALANDIA','OMAN','PAKISTAN','PALESTINA','PANAMA','PAPUA NUEVA GUINEA','PARAGUAY','PERU','POLINESIA FRANCESA','POLONIA','PORTUGAL','PUERTO RICO','QATAR','REINO UNIDO','REPUBLICA CENTROAFRICANA','REPUBLICA CHECA','REPUBLICA DEMOCRATICA DEL CONGO','REPUBLICA DOMINICANA','REPUBLICA ESLOVACA','REUNION','RUANDA','RUMANIA','RUSIA','SAHARA','SAMOA','SAN CRISTOBAL-NEVIS (ST. KITTS)','SAN MARINO','SAN VINCENTE Y LAS GRANADINAS','SANTA HELENA','SANTA LUCIA','SANTA SEDE (VATICANO)','SAO TOME & PRINCIPE','SENEGAL','SEYCHELLES','SIERRA LEONA','SINGAPUR','SIRIA','SOMALIA','SRI LANKA (CEILAN)','SUDAN','SUECIA',
'SUIZA','SUR AFRICA','SURINAM','SWAZILAND','TAILANDIA','TAIWAN','TAJIKISTAN','TANZANIA','TIMOR ORIENTAL','TOGO','TOKELAU','TONGA','TRINIDAD & TOBAGO','TUNISIA','TURKMENISTAN','TURQUIA','UCRANIA',
'UGANDA','UNION EUROPEA','URUGUAY','UZBEKISTAN','VANUATU','VENEZUELA','VIETNAM','YEMEN','YUGOSLAVIA','ZAMBIA','ZIMBABWE');
    		foreach ($arrPaises as $pais) {
    			\DB::table('paises')->insert(array(
	        		'pais' => $pais
	        	));
    		}
    }
}


